version: '3.8'
name: crediya_authentication
services:
  db_authentication: # Host name/address, pgadmin connection # select * from credi_ya.users;
    image: postgres:16.1
    container_name: crediya_users_db
    restart: always
    environment:
      POSTGRES_USER: admin # Username, pgadmin connection
      POSTGRES_PASSWORD: db_authentication # Password, pgadmin connection
      POSTGRES_DB: postgres # Maintenance database, pgadmin connection
    ports:
      - "5434:5432" # Port 5432 loalhost, port 5432 pgadmin connection
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql

  pgadmin:
      image: dpage/pgadmin4
      environment: 
        PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
        PGADMIN_DEFAULT_PASSWORD: 'admin'
      ports:
        - '81:80' # Port 80, web browser access http://localhost:81
      depends_on:
        - db_authentication  
