server:
  port: 8080
spring:
  application:
    name: "ms_authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: localhost
    port: 5434
    database: postgres
    schema: credi_ya
    username: admin
    password: db_authentication

jwt:
  secret: miClaveSuperSecretaConAlMenos32Caracteres123!
  expiration: 3600

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.server: DEBUG